opemane:
  api:
    accesstoken:
      id: hoge
      key: fuga
      url: http://localhost:3001/v1/opemane/token
server:
  servlet:
    context-path: /opemane
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  main:
    banner-mode: 'off'
