CREATE TABLE HOLIDAYS (
	HOLIDAY_DATE DATE,
	DESCLIPTION VARCHAR(255)
);

CREATE TABLE OPERATION_RECORD (
	OPERATION_DATE DATE,
	SUBJECT_CODE CHAR(10),
	SUBJECT_NAME VARCHAR(255),
	OPERATION_HOUR NUMBER(4, 2)
);

